//! Olaf keys and key shares.

use super::polynomial::CoefficientCommitment;
use crate::PublicKey;

/// The group public key generated by the SimplPedPoP protocol.
pub type GroupPublicKey = PublicKey;
/// The group public key share of each participant in the SimplPedPoP protocol.
pub type GroupPublicKeyShare = CoefficientCommitment;
